version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"  # Exponer el puerto 463 directamente en el contenedor
    networks:
      - app-network

networks:
  app-network:
    driver: bridge






